development: &default
  adapter: postgresql
  encoding: unicode
  database: hound_development
  pool: 5
  reaping_frequency: 10

test:
  <<: *default
  database: hound_test

production:
  adapter: postgresql
  encoding: unicode
  database: hound_development
  pool: 5
  reaping_frequency: 10
